#!/usr/bin/env bash
# cputils - competitive programming utilities

USAGE="\
usage:

cputils COMMAND [COMMAND_ARGS...]

COMMAND:
        new        - new file from template
        run        - run file
        cfgen      - codeforces generator from template
    

see individual commands for details

"

DIRNAME="$(dirname "$0")"

case "$1" in
	new)
		shift
		/usr/bin/env bash "$DIRNAME/cputils-new" $*
		;;
	run)
		shift
		/usr/bin/env bash "$DIRNAME/cputils-run" $*
		;;
	cfgen)
		shift
		/usr/bin/env bash "$DIRNAME/cputils-cfgen" $*
		;;
	*)
		printf "$USAGE"
		exit 1
		;;
esac

