#!/usr/bin/env bash
# cputils - competitive programming utilities

CFGDIR="$HOME/.config/cputils"

USAGE="\
usage:

cputils COMMAND [COMMAND_ARGS...]

COMMAND:
        new        - new file from template
        run        - run file
        cfgen      - codeforces generator from template
        config     - edit the configuration file
    

see individual commands for details

"

DIRNAME="$(dirname "$0")"

case "$1" in
	new)
		shift
		/usr/bin/env bash "$DIRNAME/cputils-new" $*
		;;
	run)
		shift
		/usr/bin/env bash "$DIRNAME/cputils-run" $*
		;;
	cfgen)
		shift
		/usr/bin/env bash "$DIRNAME/cputils-cfgen" $*
		;;
	config)
		shift
		source "$CFGDIR/cputils.config.bash"
		open_with_editor "$CFGDIR/cputils.config.bash"
		ret=$?

		[ "$ret" -ne 0 ] && {
			>&2 printf "\
cputils-config:

  setup your editor in the config to open the config directly;
  until then - open yourself


    "
			printf "$CFGDIR/cputils.config.bash\n"

			>&2 printf "\n\n"

			exit 1
		}

		;;
	*)
		printf "$USAGE"
		exit 1
		;;
esac

