
name: 'full-setup'

on: [push, pull_request]

jobs:
  full-setup:
    strategy:
      matrix:
        STRICT: [0, 1]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - run: STRICT=${{ matrix.STRICT }} make

