
name: 'cputils-run'

on: [push, pull_request]

jobs:
  test-cputils-run:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - run: ./setup-dev.sh
      - run: ./test.sh -f ./test/cputils-run.bats

